#!/usr/bin/env python3
"""
run_time_verification.py
========================
Self-contained NS-3 pipeline time verification for MRAM-SDVN.

What it does (in order):
  1. Backs up fix2.cc
  2. Writes cycle_timer.h (header-only chrono instrument) next to it
  3. Patches fix2.cc with PHASE_SCOPE() instrumentation lines
  4. Builds NS-3 via waf
  5. Runs the simulation (passes through any extra CLI args)
  6. Reads the resulting cycle_timing_ns3.csv
  7. Prints a full per-cycle / per-phase timing report to the terminal
  8. Restores fix2.cc from backup

All output goes to stdout. No external library needed (std::chrono in C++,
stdlib in Python).

Usage:
  python3 run_time_verification.py                          # defaults
  python3 run_time_verification.py --use-full-mode          # exercise PQC path
  python3 run_time_verification.py --budget-ms 500          # add pass/fail gate
  python3 run_time_verification.py --sim-args="--simTime=60 --N_Vehicles=50"
  python3 run_time_verification.py --ns3-dir /path/to/ns-3.35
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys
import statistics as stats
from collections import OrderedDict

# ============================================================================
# Paths (defaults match the VM layout)
# ============================================================================
DEFAULT_NS3  = "/home/sdvn_onion_telemetry/Group_51/ns-3.35"
SCRATCH_FILE = "fix2.cc"
HEADER_FILE  = "cycle_timer.h"
RESULTS_DIR  = "results"
TIMING_CSV   = "cycle_timing_ns3.csv"

# ============================================================================
# Phase model
# ============================================================================
TOPLEVEL = ["optimize", "rl", "delta_tx", "dataplane", "metrics", "watcher"]
CRYPTO   = ["crypto_kyber", "crypto_sign", "crypto_verify"]


# ============================================================================
# Step 1 — Write cycle_timer.h
# ============================================================================
CYCLE_TIMER_H = r'''
// cycle_timer.h — auto-generated by run_time_verification.py
// Header-only real-host-time instrument. Uses only <chrono> + <ctime>.
// liboqs is the thing being MEASURED; this is the stopwatch around it.
#ifndef CYCLE_TIMER_H
#define CYCLE_TIMER_H

#include <chrono>
#include <ctime>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <mutex>

namespace cycletimer {

class Sink {
public:
    static Sink& instance() { static Sink s; return s; }
    void write_row(double sim_t, double epoch,
                   const char* phase, double wall, double cpu) {
        std::lock_guard<std::mutex> lk(mtx_);
        if (!fp_) open_();
        if (!fp_) return;
        std::fprintf(fp_, "%.6f,%.6f,%s,%.6f,%.6f\n",
                     sim_t, epoch, phase, wall, cpu);
        std::fflush(fp_);
    }
private:
    Sink() = default;
    ~Sink() { if (fp_) std::fclose(fp_); }
    Sink(const Sink&) = delete;
    Sink& operator=(const Sink&) = delete;
    void open_() {
        const char* env = std::getenv("CYCLE_TIMING_CSV");
        const std::string p = env && *env ? std::string(env)
            : std::string("''' + "PLACEHOLDER_RESULTS_PATH" + r'''");
        fp_ = std::fopen(p.c_str(), "w");
        if (fp_) {
            std::fprintf(fp_, "sim_time,wall_epoch,phase,wall_ms,cpu_ms\n");
            std::fflush(fp_);
        }
    }
    std::FILE* fp_ = nullptr;
    std::mutex mtx_;
};

class PhaseScope {
public:
    PhaseScope(const char* name, double sim_t)
        : n_(name), st_(sim_t),
          t0_(std::chrono::steady_clock::now()), c0_(std::clock()) {}
    ~PhaseScope() {
        auto t1 = std::chrono::steady_clock::now();
        auto c1 = std::clock();
        double wms = std::chrono::duration<double,std::milli>(t1-t0_).count();
        double cms = 1000.0*static_cast<double>(c1-c0_)/CLOCKS_PER_SEC;
        double ep  = std::chrono::duration<double>(
            std::chrono::system_clock::now().time_since_epoch()).count();
        Sink::instance().write_row(st_, ep, n_, wms, cms);
    }
private:
    const char* n_; double st_;
    std::chrono::steady_clock::time_point t0_; std::clock_t c0_;
};

} // namespace cycletimer

#define CT_CAT_(a,b) a##b
#define CT_CAT(a,b)  CT_CAT_(a,b)
#define PHASE_SCOPE(name) \
    ::cycletimer::PhaseScope CT_CAT(_ps_,__LINE__)((name), Now().GetSeconds())

#endif
'''.lstrip()


# ============================================================================
# Step 2 — Patch fix2.cc
# ============================================================================
def patch_fix2(src_path):
    """
    Apply instrumentation patches to fix2.cc. Returns True if all succeeded.
    Patches are idempotent — re-running on an already-patched file is safe.
    """
    with open(src_path, "r") as f:
        code = f.read()

    if "PHASE_SCOPE" in code:
        print("[patch] fix2.cc already instrumented — skipping patch")
        return True

    original = code
    ok = True

    # --- (a) Add #include "cycle_timer.h" after #include <oqs/oqs.h> --------
    marker = '#include <oqs/oqs.h>'
    if marker in code:
        code = code.replace(marker, marker + '\n#include "cycle_timer.h"', 1)
        print("[patch] added #include \"cycle_timer.h\"")
    else:
        print("[patch] WARNING: could not find oqs include to anchor header insertion")
        ok = False

    # --- (b) Phase scopes in top-level functions -----------------------------
    #     Pattern: void func_name()\n{\n  ->  void func_name()\n{\n  PHASE_SCOPE(..);
    phase_funcs = [
        ("run_optimization_link_lifetime", "optimize"),
        ("run_proposed_RL",                "rl"),
        ("transmit_delta_values",          "delta_tx"),
        ("initiate_all_flows",             "dataplane"),
        ("calculate_performance_evaluation_metrics", "metrics"),
        ("dump_watcher_cycle_csv",         "watcher"),
    ]
    for func, label in phase_funcs:
        target = f"void {func}()\n{{"
        replacement = f"void {func}()\n{{\n\tPHASE_SCOPE(\"{label}\");"
        if target in code:
            code = code.replace(target, replacement, 1)
            print(f"[patch] instrumented {func} -> \"{label}\"")
        else:
            print(f"[patch] WARNING: could not find {func}() signature")
            ok = False

    # --- (c) Crypto sub-slices inside run_proposed_RL ------------------------
    # Wrap lkh_receive_keys
    kyber_old = "\tlkh_receive_keys((uint32_t)data_gathering_cycle_number);"
    kyber_new = "\t{ PHASE_SCOPE(\"crypto_kyber\"); lkh_receive_keys((uint32_t)data_gathering_cycle_number); }"
    if kyber_old in code:
        code = code.replace(kyber_old, kyber_new, 1)
        print("[patch] instrumented lkh_receive_keys -> \"crypto_kyber\"")
    else:
        print("[patch] WARNING: could not find lkh_receive_keys call to wrap")

    # Wrap lkh_sign_and_encrypt_flow_rules
    sign_old = "\t\tlkh_sign_and_encrypt_flow_rules((uint32_t)data_gathering_cycle_number);"
    sign_new = "\t\t{ PHASE_SCOPE(\"crypto_sign\"); lkh_sign_and_encrypt_flow_rules((uint32_t)data_gathering_cycle_number); }"
    if sign_old in code:
        code = code.replace(sign_old, sign_new, 1)
        print("[patch] instrumented lkh_sign_and_encrypt -> \"crypto_sign\"")
    else:
        print("[patch] WARNING: could not find lkh_sign_and_encrypt call to wrap")

    # Wrap lkh_verify_and_decrypt_flow_rules
    vrfy_old = "\t\tlkh_verify_and_decrypt_flow_rules((uint32_t)data_gathering_cycle_number);"
    vrfy_new = "\t\t{ PHASE_SCOPE(\"crypto_verify\"); lkh_verify_and_decrypt_flow_rules((uint32_t)data_gathering_cycle_number); }"
    if vrfy_old in code:
        code = code.replace(vrfy_old, vrfy_new, 1)
        print("[patch] instrumented lkh_verify_and_decrypt -> \"crypto_verify\"")
    else:
        print("[patch] WARNING: could not find lkh_verify_and_decrypt call to wrap")

    with open(src_path, "w") as f:
        f.write(code)

    print(f"[patch] done — {len(code) - len(original):+d} bytes delta")
    return ok


# ============================================================================
# Step 6 — Read timing CSV and build per-cycle table
# ============================================================================
CYCLE_ANCHOR_ORDER = ["optimize", "rl", "delta_tx", "dataplane", "metrics"]

def read_timing_csv(path):
    if not os.path.isfile(path):
        return []
    rows = []
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            try:
                rows.append({
                    "sim_time":   float(r["sim_time"]),
                    "wall_epoch": float(r["wall_epoch"]),
                    "phase":      r["phase"].strip(),
                    "wall_ms":    float(r["wall_ms"]),
                    "cpu_ms":     float(r.get("cpu_ms", "nan") or "nan"),
                })
            except (KeyError, ValueError):
                continue
    if not rows:
        return []
    rows.sort(key=lambda r: (r["sim_time"], r["wall_epoch"]))

    # pick the anchor phase actually present
    present = {r["phase"] for r in rows}
    anchor = next((p for p in CYCLE_ANCHOR_ORDER if p in present), None)
    if not anchor:
        anchor = rows[0]["phase"]

    cycles = []
    cur = None
    for r in rows:
        if r["phase"] == anchor:
            if cur is not None:
                cycles.append(cur)
            cur = {"anchor_sim": r["sim_time"],
                   "anchor_epoch": r["wall_epoch"],
                   "end_epoch": r["wall_epoch"],
                   "phases": OrderedDict()}
        if cur is None:
            continue
        cur["phases"][r["phase"]] = {"wall_ms": r["wall_ms"], "cpu_ms": r["cpu_ms"]}
        cur["end_epoch"] = max(cur["end_epoch"], r["wall_epoch"])
    if cur is not None:
        cycles.append(cur)

    for i, c in enumerate(cycles, 1):
        c["index"] = i
    return cycles


# ============================================================================
# Step 7 — Print report
# ============================================================================
def _f(v, w=10, p=3):
    if v is None or v != v:  # nan check
        return f"{'—':>{w}}"
    return f"{v:>{w}.{p}f}"

def _summarize(vals):
    v = [x for x in vals if x is not None and x == x]
    if not v:
        return None
    v.sort()
    n = len(v)
    return {
        "n": n, "mean": stats.fmean(v), "median": stats.median(v),
        "stdev": stats.pstdev(v) if n > 1 else 0.0,
        "p95": v[min(n-1, int(round(0.95*(n-1))))],
        "min": v[0], "max": v[-1],
    }

def print_report(cycles, budget_ms):
    W = 80
    print()
    print("=" * W)
    print("  MRAM-SDVN  NS-3  TIME  VERIFICATION")
    print("  Real host time per cycle (computational & cryptographic overhead)")
    print("=" * W)
    print(f"  Cycles measured : {len(cycles)}")
    if not cycles:
        print("  ERROR: no timing data found. Did the simulation run?")
        print("=" * W)
        return False
    print()

    # ---- build per-cycle records ----
    records = []
    for c in cycles:
        ph = c["phases"]
        ns3_total = sum(ph[p]["wall_ms"] for p in TOPLEVEL if p in ph)
        crypto_total = sum(ph[p]["wall_ms"] for p in CRYPTO if p in ph)
        inter = None
        if len(records) > 0:
            inter = c["anchor_epoch"] - records[-1]["_epoch"]
        records.append({
            "cycle": c["index"],
            "phases": {p: ph[p]["wall_ms"] for p in (TOPLEVEL + CRYPTO) if p in ph},
            "ns3_total": ns3_total,
            "crypto_total": crypto_total,
            "inter_s": inter,
            "_epoch": c["anchor_epoch"],
        })

    # ---- per-cycle table ----
    all_phases = [p for p in (TOPLEVEL + CRYPTO)
                  if any(p in r["phases"] for r in records)]

    hdr = ["cycle"] + all_phases + ["NS3_TOTAL", "crypto", "inter(s)"]
    print("PER-CYCLE BREAKDOWN  (all values in ms, inter-cycle in seconds)")
    print("-" * W)
    print("  ".join(f"{h:>12}" for h in hdr))

    for r in records:
        row = [f"{r['cycle']:>12}"]
        for p in all_phases:
            row.append(_f(r["phases"].get(p), 12))
        row.append(_f(r["ns3_total"], 12))
        row.append(_f(r["crypto_total"], 12))
        row.append(_f(r["inter_s"], 12))
        print("  ".join(row))
    print()

    # ---- aggregates ----
    print("AGGREGATE STATISTICS")
    print("-" * W)
    print(f"{'':>20}  {'n':>4}  {'mean':>10}  {'median':>10}  "
          f"{'p95':>10}  {'max':>10}  {'stdev':>10}")

    def agg(label, vals):
        s = _summarize(vals)
        if not s:
            return
        print(f"{label:>20}  {s['n']:>4}  {_f(s['mean'])}  {_f(s['median'])}  "
              f"{_f(s['p95'])}  {_f(s['max'])}  {_f(s['stdev'])}")

    print("  NS-3 host phases (ms):")
    for p in TOPLEVEL:
        vals = [r["phases"].get(p) for r in records]
        agg(p, vals)
    print("  PQC crypto sub-slices (ms):")
    for p in CRYPTO:
        vals = [r["phases"].get(p) for r in records]
        agg(p, vals)
    print("  Totals:")
    agg("NS-3 host TOTAL", [r["ns3_total"] for r in records])
    agg("of which crypto", [r["crypto_total"] for r in records])
    agg("inter-cycle (s)", [r["inter_s"] for r in records])
    print()

    # ---- crypto fraction ----
    s_host = _summarize([r["ns3_total"] for r in records])
    s_cry  = _summarize([r["crypto_total"] for r in records])
    if s_host and s_cry and s_host["mean"] > 0:
        frac = 100.0 * s_cry["mean"] / s_host["mean"]
        print(f"Crypto share of NS-3 host time (mean): {frac:.2f}%  "
              f"({s_cry['mean']:.3f} ms / {s_host['mean']:.3f} ms)")
        print()

    # ---- budget gate ----
    verdict = None
    if budget_ms is not None:
        print("BUDGET GATE")
        print("-" * W)
        vals = [r["ns3_total"] for r in records]
        s = _summarize(vals)
        if s:
            over = [v for v in vals if v is not None and v > budget_ms]
            verdict = "PASS" if not over else "FAIL"
            print(f"  Budget        : {budget_ms:.3f} ms per cycle")
            print(f"  Observed p95  : {s['p95']:.3f} ms    max: {s['max']:.3f} ms")
            print(f"  Cycles > budget : {len(over)} / {s['n']}")
            print(f"  VERDICT       : {verdict}")
        print()

    print("=" * W)
    if verdict:
        print(f"  RESULT: {verdict}")
    else:
        print("  RESULT: reported (no --budget-ms set)")
    print("=" * W)
    print()
    return verdict != "FAIL"


# ============================================================================
# Main
# ============================================================================
def main():
    ap = argparse.ArgumentParser(
        description="Patch, build, run NS-3, and verify per-phase timing.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("--ns3-dir", default=DEFAULT_NS3,
                    help="Path to the ns-3.35 directory")
    ap.add_argument("--scratch-file", default=SCRATCH_FILE,
                    help="Name of the scratch file (inside scratch/)")
    ap.add_argument("--use-full-mode", action="store_true",
                    help="Pass --use_full_mode=true to NS-3 (exercises PQC path)")
    ap.add_argument("--sim-args", default="",
                    help="Extra CLI args passed to the NS-3 simulation "
                         "(e.g. '--simTime=60 --N_Vehicles=50')")
    ap.add_argument("--budget-ms", type=float, default=None,
                    help="Optional per-cycle host-time budget (ms) for PASS/FAIL")
    ap.add_argument("--skip-build", action="store_true",
                    help="Skip waf build (use if already built)")
    ap.add_argument("--skip-run", action="store_true",
                    help="Skip simulation run (just analyse existing CSV)")
    ap.add_argument("--no-restore", action="store_true",
                    help="Do NOT restore fix2.cc from backup after the run")
    args = ap.parse_args()

    ns3       = os.path.abspath(args.ns3_dir)
    scratch   = os.path.join(ns3, "scratch")
    src_path  = os.path.join(scratch, args.scratch_file)
    bak_path  = src_path + ".bak_timing"
    hdr_path  = os.path.join(scratch, HEADER_FILE)
    res_dir   = os.path.join(ns3, RESULTS_DIR)
    csv_path  = os.path.join(res_dir, TIMING_CSV)
    prog_name = os.path.splitext(args.scratch_file)[0]  # "fix2"

    if not args.skip_run:
        # ---- Verify paths ----
        if not os.path.isdir(ns3):
            sys.exit(f"ERROR: NS-3 directory not found: {ns3}")
        if not os.path.isfile(src_path):
            sys.exit(f"ERROR: source not found: {src_path}")

        # ---- Step 1: backup ----
        if not os.path.isfile(bak_path):
            shutil.copy2(src_path, bak_path)
            print(f"[backup] {src_path} -> {bak_path}")
        else:
            # Restore clean copy before re-patching (idempotent)
            shutil.copy2(bak_path, src_path)
            print(f"[backup] restored clean copy from {bak_path}")

        # ---- Step 2: write cycle_timer.h ----
        actual_csv_path = os.path.join(res_dir, TIMING_CSV)
        header_code = CYCLE_TIMER_H.replace("PLACEHOLDER_RESULTS_PATH",
                                            actual_csv_path)
        with open(hdr_path, "w") as f:
            f.write(header_code)
        print(f"[header] wrote {hdr_path}")

        # ---- Step 3: patch fix2.cc ----
        os.makedirs(res_dir, exist_ok=True)
        if not patch_fix2(src_path):
            print("[patch] WARNING: some patches could not be applied (see above)")

        # ---- Step 4: build ----
        if not args.skip_build:
            print("\n[build] running waf ...")
            build_cmd = ["./waf"]
            rc = subprocess.call(build_cmd, cwd=ns3)
            if rc != 0:
                print(f"[build] waf returned {rc}")
                if not args.no_restore:
                    shutil.copy2(bak_path, src_path)
                    print(f"[restore] fix2.cc restored from backup")
                sys.exit(f"ERROR: build failed (exit {rc})")
            print("[build] success\n")

        # ---- Step 5: run simulation ----
        # Remove old CSV so we only see fresh data
        if os.path.isfile(csv_path):
            os.remove(csv_path)

        run_str = prog_name
        if args.use_full_mode:
            run_str += " --use_full_mode=true"
        if args.sim_args:
            run_str += " " + args.sim_args

        print(f"[run] ./waf --run \"{run_str}\"")
        print("-" * 60)
        rc = subprocess.call(["./waf", "--run", run_str], cwd=ns3)
        print("-" * 60)
        if rc != 0:
            print(f"[run] simulation returned {rc}")

        # ---- Restore backup ----
        if not args.no_restore:
            shutil.copy2(bak_path, src_path)
            if os.path.isfile(hdr_path):
                os.remove(hdr_path)
            print(f"[restore] fix2.cc and cycle_timer.h cleaned up")

    # ---- Step 6 & 7: read CSV and print report ----
    if not os.path.isfile(csv_path):
        sys.exit(f"ERROR: timing CSV not found at {csv_path}\n"
                 f"       Did the simulation run and reach at least one cycle?")

    cycles = read_timing_csv(csv_path)
    passed = print_report(cycles, args.budget_ms)

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
